name: Unit Tests

on:
  push:
    branches: [ "*" ]  # Run on all branch pushes
  pull_request:
    branches: [ "main", "master", "dev", "develop" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]  # Test on minimum and recommended versions

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dos2unix file

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r VMEncryption/requirements.txt
        # Install additional test dependencies
        pip install pytest-cov

    - name: Set up Python path for tests
      run: |
        echo "PYTHONPATH=${{ github.workspace }}/VMEncryption/main:${{ github.workspace }}/VMEncryption:${{ github.workspace }}/Utils:${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run VMEncryption unit tests
      working-directory: VMEncryption/main
      run: |
        python -m pytest test/ -v --tb=short || python -m unittest discover test -v

    - name: Run Utils unit tests  
      working-directory: Utils
      run: |
        python -m pytest test/ -v --tb=short || python -m unittest discover test -v

    - name: Run code quality checks
      if: matrix.python-version == '3.11'
      run: |
        pip install flake8
        # Check for syntax errors and undefined names
        flake8 VMEncryption/main/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 Utils/ --count --select=E9,F63,F7,F82 --show-source --statistics
