name: Unit Tests

on:
  push:
    branches: [ "*" ]  # Run on all branch pushes
  pull_request:
    branches: [ "main", "master", "dev", "develop" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]  # Test on minimum and recommended versions

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dos2unix file

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r VMEncryption/requirements.txt
        # Install additional test dependencies
        pip install pytest-cov coverage

    - name: Set up Python path for tests
      run: |
        echo "PYTHONPATH=${{ github.workspace }}/VMEncryption/main:${{ github.workspace }}/VMEncryption:${{ github.workspace }}/Utils:${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run VMEncryption tests with coverage
      working-directory: VMEncryption/main
      run: |
        echo "=== Running VMEncryption tests ==="
        python -m pytest test/ -v --cov=. --cov-report=term --cov-report=xml || \
        python -m pytest test/ -v || \
        python -m unittest discover test -v

    - name: Run Utils tests 
      working-directory: Utils
      continue-on-error: true
      run: |
        echo "=== Running Utils tests (Python 3 compatible only) ==="
        python -m pytest test/test_logutil.py -v || echo "Utils tests skipped"

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./VMEncryption/main/coverage.xml
        fail_ci_if_error: false

    - name: Basic syntax check
      if: matrix.python-version == '3.11'
      run: |
        echo "Running basic Python syntax checks..."
        # Simple syntax check using python compile
        python -m py_compile VMEncryption/main/*.py || echo "Some VMEncryption files have syntax issues"
        python -m py_compile Utils/*.py || echo "Some Utils files have syntax issues"
        echo "Syntax check completed"
